---
# tasks file for freeipaclient
#
- name: remove old ldap cruft
  yum:
    name:
    - openldap
    - sssd
    - openldap-clients
    - nss-pam-ldapd
    - nscd
    state: absent
  file:
    path: /etc/sssd/sssd.conf
    state: absent
  file:
    path: /etc/nsswitch.conf
    state: absent
  file:
    path: /etc/home.map
    state: absent

- name: ensure firewalld is disabled
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: install ipa client
  yum:
    name: ipa-client
    state: latest


