---
- name: Install mysql-server mysql
  hosts: database6
  become: yes
  become_method: sudo
  gather_facts: true
  tags: [database]
  tasks:
        - name: Update the software package repository
          yum:
                update_cache: yes

        - name: Install MySQL
          yum:
                name: mysql-server, libselinux-python 
                state: latest

        - name: copy my.cnf
          copy:
            src: /ansible/roles/files/etc/my.cnf
            dest: /etc/my.cnf
            mode: 0644
       
        - name: enable mysql
          service:
            name: mysqld
            state: restarted
            enabled: yes


