---
- name: restart ntpd
  hosts: all
  become_user: root
  become: true
  
  tasks:

  - name: disable selinux
    selinux:
      policy: targeted
      state: permissive

  - name: enable ntpd
    service:
      name: ntpd
      state: started

  - name: Restart ntpd
    service:
      name: ntpd
      state: reloaded
