---
# tasks file for ldap
- name: install ldap
  yum:
    name:
    - openldap 
    - openldap-clients 
    - openldap-servers 
    - openssl
    - expect
    - pexpect
    - httpd
    - epel-release
#    - phpldapadmin
    - migrationtools
    state: latest

#- name: Automatically insert password to slappasswd
#  expect:
#    command: /usr/sbin/slappasswd -c
#    responses:
#     (?i*)password: 'password'
#  no_log: false

# Run slappasswd manually and paste the hashed version into your ldif
# files as olcRootPW

#- name: slapassword
#  command: {{ item }}
#    with_items: 
#      - slappasswd > slapswd
#      - var=slapswd
#      - sed -i '/^olcRootPW:*/c#' hdb.ldif
#      - echo "olcRootPW: $var" >> hdb.ldif

- name: start services
  service:
    name: slapd
    state: started
    enabled: yes

- name: create ldif files
  template:
   src: hdb.ldif
   dest: /root/hdb.ldif

- name: run ldapmodify
  shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f /root/hdb.ldif
  args:
    executable: /bin/bash

- name: configure monitoring privs
  template:
    src: monitor.ldif
    dest: /root/monitor.ldif

- name: run ldapmodify
  shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f monitor.ldif
  args:
    executable: /bin/bash
    chdir: /root/

#- name: listen on SSL
#  template:
#    src: ldapconfig
#    dest: /etc/sysconfig/ldap

#- name: generate ssl certificate
#  script: /ansible/roles/ldap/templates/ssl.sh

#- name: deal with keys
#  template:
#    src: key.ldif
#   dest: /root/key.ldif

#- name: run ldapmodify
#  shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f key.ldif
#  args:
#    executable: /bin/bash

#- name: copy cert
#  command: cp /etc/openldap/certs/cacert.pem /var/www/html/

- name: restart slapd
  service:
    name: slapd
    state: restarted
    enabled: yes

- name: cosine
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
 
- name: nis
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif

- name: inetorgperson
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

- name: install phpmyadmin
  yum:
    name: phpmyadmin
    state: latest 

- name: start httpd
  service:
    state: started
    enabled: yes


