---
# tasks file for nfsclient
#- name: Include overrides specific to RHEL 7.
#  include_vars: RedHat-7.yml
#  when:
#    - ansible_os_family == 'RedHat'


- name: install nfs-utils
  yum:
    name: 
    - nfs-utils
    - autofs
    state: latest

- name: start and enable services
  service:
    name: rpcbind
    state: started
    enabled: yes
#    name: nfs
#    state: started
#    enabled: yes
- include_tasks: setup-RedHat.yml
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

#- name: edit fstab
#  shell:  echo 'prdx-nfs15:/var/share      /share     nfs      rw,sync,intr,soft,timeo=100      0 0' >> /etc/fstab

#- name: unmount share dir if already mounted, hopefully fixes bug
#  command: umount -l /share
#  mount:
#    path: /share
#    state: unmounted

#- name: create share dir
#  file:
#    path: /share
#    state: directory

- name: mount nfs dir
  mount:
    path: /share
    src: prdx-nfs15:/var/share
    fstype: nfs
    state: mounted

#- name: mount dir
#  command: mount -t nfs nfs:/var/share /share

#- name: mount
#  command: mount -a

- name: insert autofs master file
  template:
    src: share.autofs
    dest: /etc/auto.master
- name: insert autofs map file
  template:
    src: auto.share
    dest: /etc/auto.share

- name: start autofs
  service:
    name: autofs
    state: started
    enabled: yes

