---
# tasks file for nfsclient
  - name: install nfs-utils
    yum:
      name: nfs-utils
      state: latest

  - name: start and enable services
    service:
      name: rpcbind
      state: started
      enabled: yes
      name: nfs-server
      state: started
      enabled: yes
      name: nfs-lock
      state: started
      enabled: yes
      name: nfs-idmap
      state: started
      enabled: yes

  - name: create share dir
    file:
      path: /share
      state: directory
      mode: 0755

  - name: mount nfs dir
    mount:
      path: /share
      src: prdx-nfs15:/var/share
      fstype: nfs
      state: present
