---
- name: start nfs idmap service for rh7     
  service:
    name: nfs-idmap
    state: started
    enabled: yes
    name: nfs-lock
    state: started
    enabled: yes
    name: nfs-server
    state: started
    enabled: yes

