---
- name: start nfs idmap service for rh7     
  service:
    name: nfs-idmap
    state: stopped 
    enabled: no
    name: nfs-lock
    state: stopped
    enabled: no
    name: nfs-server
    state: stopped
    enabled: no

